---
#This playbook will compare the running configuration against a reference file & note the differences
- hosts: somehost
  gather_facts: false
  connection: network_cli
  remote_user: admin
  become: yes
  become_method: enable
  tasks:
    - name: compare config against master
      ios_config:
        diff_against: intended
        intended_config: "{{ lookup('file', 'master.cfg') }}"
        match: exact